# Generated by Django 4.2 on 2023-05-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_alter_tasklist_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['id']},
        ),
    ]
